sudo: required
services:
  - docker

before_install:
  - docker build -t allstar98k/pizza_shop_app:latest .

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "DockerPizzaV1"
  env: "DockerPizzaV1-env"
  # name of the bucket in S3 that travis will upload the zip file to
  bucket_name: "elasticbeanstalk-ap-south-1-642303465584"
  bucket_path: "DockerPizzaV1"
  on:
    branch: master
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
